name: atom_flutter
version: 0.1.2
description: A Flutter development environment for Atom.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/atom-flutter

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  atom:
    git: https://github.com/dart-atom/atom.dart.git
    # path: ../../atom/atom.dart
  logging: ^0.11.0
  usage: ^1.1.0

dev_dependencies:
  # dev_compiler: 0.1.15
  grinder: ^0.8.0+1
