name: atom_flutter_dev
version: 0.0.1
description: A Flutter development environment for Atom.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/atom-flutter-dev

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  # func: ^0.1.0
  # js: 0.6.0-beta.7
  # logging: ^0.11.0

dev_dependencies:
  grinder: ^0.8.0
